'use strict';

/**
 * trib-memory session-start hook
 *
 * Loads context.md (memory bridge) and injects as additionalContext.
 * context.md is generated by memory-cycle from SQLite memory store.
 */

const fs = require('fs');
const path = require('path');

// Read hook event from stdin for session filtering
let _event = {};
try {
  const _input = fs.readFileSync(0, 'utf8');
  if (_input) _event = JSON.parse(_input);
} catch {}

// Safety filters: only inject context for main interactive sessions
if (_event.isSidechain) process.exit(0);
if (_event.agentId) process.exit(0);
if (_event.kind && _event.kind !== 'interactive') process.exit(0);

const DATA_DIR = process.env.CLAUDE_PLUGIN_DATA;
if (!DATA_DIR) process.exit(0);

const CONTEXT_FILE = path.join(DATA_DIR, 'history', 'context.md');

let content;
try {
  content = fs.readFileSync(CONTEXT_FILE, 'utf8').trim();
} catch {
  // No context.md yet — first run or memory cycle hasn't generated it
  process.exit(0);
}

if (content) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'SessionStart',
      additionalContext: content
    }
  }));
}
